name: Automerge Dependabot pull requests
on:
  pull_request:
    branches:
      - develop
jobs:
  lint-test-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1.0
          cache: "yarn"
      - run: corepack enable yarn && yarn set version ./.yarn/releases/yarn-3.2.1.cjs
      - name: install dependencies
        run: yarn install --production=false
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test-ci
      - name: merge
        uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
