name: Lint and test code in pull requests
on:
  pull_request:
    branches:
      - main
jobs:
  check-pr-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.4.1
      - run: yarn install --production=false
      - run: yarn lint
      - run: yarn test-automerge
