name: Lint and test code in pull requests
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  check-pr-quality:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1.0
          cache: "yarn"
      - run: corepack enable yarn && yarn set version ./.yarn/releases/yarn-3.2.1.cjs
      - run: yarn install
      - run: yarn lint
      - run: yarn test
